INSERT INTO CONTENT_OF_WAREHOUSE (INVENTORY_ID, MATERIAL_OBJECT_NAME, COMMISSIONING_DATE)
SELECT
   MY_XML.CONTENT.query('INVENTORY_ID').value('.', 'int'),
   MY_XML.CONTENT.query('MATERIAL_OBJECT_NAME').value('.', 'NVARCHAR(100)'),
   MY_XML.CONTENT.query('COMMISSIONING_DATE').value('.', 'datetime')
FROM (SELECT CAST(MY_XML AS xml)
      FROM OPENROWSET(BULK 'Z:\material_report_dbo_CONTENT_OF_WAREHOUSE.xml', SINGLE_BLOB) AS T(MY_XML)) AS T(MY_XML)
      CROSS APPLY MY_XML.nodes('data/row') AS MY_XML (CONTENT);