CREATE TABLE MATERIAL_OBJECT(
    NAME nvarchar(100) PRIMARY KEY NOT NULL,
    SYSTEM_TYPE nvarchar(10),
    COMMENTS nvarchar(1000)
)

CREATE TABLE CONSTITUENT_COMPONENT_TYPE(
    ID int IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    NAME nvarchar(100) NOT NULL,
    RECYCLABLE BIT DEFAULT 0,
    DESCRIPTION nvarchar(1000)
)

CREATE TABLE CONSTITUENT_COMPONENT(
    ID int IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    CONSTITUENT_COMPONENT_TYPE_ID int,
    COUNT FLOAT(53),
    COUNT_UNIT nvarchar(2),
    MATERIAL_OBJECT_NAME nvarchar(100),
    FOREIGN KEY (CONSTITUENT_COMPONENT_TYPE_ID) REFERENCES CONSTITUENT_COMPONENT_TYPE(ID),
    FOREIGN KEY (MATERIAL_OBJECT_NAME) REFERENCES MATERIAL_OBJECT(NAME)
)

CREATE SEQUENCE ContentWarehouseSequence START WITH 1 INCREMENT BY 1;

CREATE TABLE CONTENT_OF_WAREHOUSE(
    INVENTORY_ID int PRIMARY KEY NOT NULL,
    MATERIAL_OBJECT_NAME nvarchar(100) NOT NULL,
    COMMISSIONING_DATE datetime NOT NULL,
    FOREIGN KEY (MATERIAL_OBJECT_NAME) REFERENCES MATERIAL_OBJECT(NAME)
)

CREATE TABLE BROKEN_CONTENT_OF_WAREHOUSE(
    INVENTORY_ID int PRIMARY KEY NOT NULL,
    MATERIAL_OBJECT_NAME nvarchar(100) NOT NULL,
    COMMISSIONING_DATE datetime NOT NULL,
    RESTORATION_COAST float(53),
    DEPRECATION float(53),
    FOREIGN KEY (MATERIAL_OBJECT_NAME) REFERENCES MATERIAL_OBJECT(NAME)
)

CREATE TABLE DECOMMISSIONED_CONTENT_OF_WAREHOUSE(
    INVENTORY_ID int PRIMARY KEY NOT NULL,
    MATERIAL_OBJECT_NAME nvarchar(100) NOT NULL,
    COMMISSIONING_DATE datetime NOT NULL,
    RESTORATION_COAST float(53),
    DEPRECATION float(53),
    DECOMMISSIONING_DATE datetime NOT NULL,
    FOREIGN KEY (MATERIAL_OBJECT_NAME) REFERENCES MATERIAL_OBJECT(NAME)
)

CREATE TABLE ACCOUNT(
    LOGIN nvarchar(50) PRIMARY KEY NOT NULL,
    HASH_PASSWORD nvarchar(32) NOT NULL,
    FULL_NAME nvarchar(100) NOT NULL,
    ACCESS_LEVEL int NOT NULL,
    PHOTO VARBINARY(MAX)
);