DROP TABLE ACCOUNT;
DROP TABLE DECOMMISSIONED_CONTENT_OF_WAREHOUSE;
DROP TABLE BROKEN_CONTENT_OF_WAREHOUSE;
DROP TABLE CONTENT_OF_WAREHOUSE;
DROP TABLE CONSTITUENT_COMPONENT;
DROP TABLE CONSTITUENT_COMPONENT_TYPE;
DROP TABLE MATERIAL_OBJECT;